// Mocks generated by Mockito 5.4.6 from annotations
// in planfit/test/auto_backup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:planfit/core/db/app_database.dart' as _i4;
import 'package:planfit/features/schedule/domain/ports.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationPort extends _i1.Mock implements _i2.NotificationPort {
  MockNotificationPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> scheduleForEvent(_i4.EventRow? event) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleForEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelForEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelForEvent, [eventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleForTodo(_i4.TodoRow? todo) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleForTodo, [todo]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelForTodo(String? todoId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelForTodo, [todoId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CalendarPort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarPort extends _i1.Mock implements _i2.CalendarPort {
  MockCalendarPort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  _i3.Future<String?> pushEvent(_i4.EventRow? event) =>
      (super.noSuchMethod(
            Invocation.method(#pushEvent, [event]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteEvent(_i4.EventRow? event) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
