// Mocks generated by Mockito 5.4.6 from annotations
// in planfit/test/calendar_import_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:device_calendar_plus/device_calendar_plus.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:planfit/core/calendar_sync/calendar_service.dart' as _i2;
import 'package:planfit/core/db/app_database.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarService extends _i1.Mock implements _i2.CalendarService {
  MockCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enabled =>
      (super.noSuchMethod(Invocation.getter(#enabled), returnValue: false)
          as bool);

  @override
  bool get autoImportEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#autoImportEnabled),
            returnValue: false,
          )
          as bool);

  @override
  Set<String> get subscribedCalendarIds =>
      (super.noSuchMethod(
            Invocation.getter(#subscribedCalendarIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  bool get isEnabled =>
      (super.noSuchMethod(Invocation.getter(#isEnabled), returnValue: false)
          as bool);

  @override
  set enabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#enabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set targetCalendarId(String? value) => super.noSuchMethod(
    Invocation.setter(#targetCalendarId, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoImportEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#autoImportEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set subscribedCalendarIds(Set<String>? value) => super.noSuchMethod(
    Invocation.setter(#subscribedCalendarIds, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> hasFullAccess() =>
      (super.noSuchMethod(
            Invocation.method(#hasFullAccess, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestAccess() =>
      (super.noSuchMethod(
            Invocation.method(#requestAccess, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Calendar>> writableCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#writableCalendars, []),
            returnValue: _i3.Future<List<_i4.Calendar>>.value(<_i4.Calendar>[]),
          )
          as _i3.Future<List<_i4.Calendar>>);

  @override
  _i3.Future<List<_i4.Calendar>> allCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#allCalendars, []),
            returnValue: _i3.Future<List<_i4.Calendar>>.value(<_i4.Calendar>[]),
          )
          as _i3.Future<List<_i4.Calendar>>);

  @override
  _i3.Future<List<_i4.Event>> listEvents(
    String? calendarId, {
    required DateTime? from,
    required DateTime? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listEvents,
              [calendarId],
              {#from: from, #to: to},
            ),
            returnValue: _i3.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i3.Future<List<_i4.Event>>);

  @override
  _i3.Future<String?> resolveTargetCalendarId() =>
      (super.noSuchMethod(
            Invocation.method(#resolveTargetCalendarId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> pushEvent(_i5.EventRow? event) =>
      (super.noSuchMethod(
            Invocation.method(#pushEvent, [event]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteEvent(_i5.EventRow? event) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Event?> fetchEvent(String? osEventId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEvent, [osEventId]),
            returnValue: _i3.Future<_i4.Event?>.value(),
          )
          as _i3.Future<_i4.Event?>);
}
