// Mocks generated by Mockito 5.4.6 from annotations
// in planfit/test/calendar_service_push_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:device_calendar_plus_platform_interface/device_calendar_plus_platform_interface.dart'
    as _i2;
import 'package:device_calendar_plus_platform_interface/src/create_calendar_options.dart'
    as _i4;
import 'package:device_calendar_plus_platform_interface/src/patch.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DeviceCalendarPlusPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceCalendarPlusPlatform extends _i1.Mock
    implements _i2.DeviceCalendarPlusPlatform {
  MockDeviceCalendarPlusPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> requestPermissions(bool? writeOnly) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, [writeOnly]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> hasPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermissions, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#listCalendars, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<String> createCalendar(
    String? name,
    String? colorHex,
    _i4.CreateCalendarPlatformOptions? platformOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCalendar, [
              name,
              colorHex,
              platformOptions,
            ]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createCalendar, [
                  name,
                  colorHex,
                  platformOptions,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listSources() =>
      (super.noSuchMethod(
            Invocation.method(#listSources, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> updateCalendar(
    String? calendarId,
    String? name,
    String? colorHex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCalendar, [calendarId, name, colorHex]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCalendar(String? calendarId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCalendar, [calendarId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listEvents(
    DateTime? startDate,
    DateTime? endDate,
    List<String>? calendarIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listEvents, [startDate, endDate, calendarIds]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>?> getEvent(String? eventId, int? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [eventId, timestamp]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> showEventModal(
    String? eventId,
    int? timestamp, {
    bool? edit = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #showEventModal,
              [eventId, timestamp],
              {#edit: edit},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> createEvent(
    String? calendarId,
    String? title,
    DateTime? startDate,
    DateTime? endDate,
    bool? isAllDay,
    String? description,
    String? location,
    String? url,
    String? timeZone,
    String? availability,
    String? recurrenceRule,
    List<int>? reminders,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [
              calendarId,
              title,
              startDate,
              endDate,
              isAllDay,
              description,
              location,
              url,
              timeZone,
              availability,
              recurrenceRule,
              reminders,
            ]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createEvent, [
                  calendarId,
                  title,
                  startDate,
                  endDate,
                  isAllDay,
                  description,
                  location,
                  url,
                  timeZone,
                  availability,
                  recurrenceRule,
                  reminders,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteEvent(String? eventId, {int? timestamp}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [eventId], {#timestamp: timestamp}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateEvent(
    String? eventId, {
    int? timestamp,
    String? title,
    DateTime? startDate,
    DateTime? endDate,
    _i6.Patch<String>? description,
    _i6.Patch<String>? location,
    _i6.Patch<String>? url,
    bool? isAllDay,
    String? timeZone,
    String? availability,
    _i6.Patch<List<int>>? reminders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateEvent,
              [eventId],
              {
                #timestamp: timestamp,
                #title: title,
                #startDate: startDate,
                #endDate: endDate,
                #description: description,
                #location: location,
                #url: url,
                #isAllDay: isAllDay,
                #timeZone: timeZone,
                #availability: availability,
                #reminders: reminders,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> updateRecurring(
    String? eventId,
    int? timestamp,
    String? span, {
    String? title,
    DateTime? start,
    int? durationMinutes,
    _i6.Patch<String>? description,
    _i6.Patch<String>? location,
    _i6.Patch<String>? url,
    bool? isAllDay,
    String? timeZone,
    String? availability,
    _i6.Patch<String>? recurrenceRule,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRecurring,
              [eventId, timestamp, span],
              {
                #title: title,
                #start: start,
                #durationMinutes: durationMinutes,
                #description: description,
                #location: location,
                #url: url,
                #isAllDay: isAllDay,
                #timeZone: timeZone,
                #availability: availability,
                #recurrenceRule: recurrenceRule,
              },
            ),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #updateRecurring,
                  [eventId, timestamp, span],
                  {
                    #title: title,
                    #start: start,
                    #durationMinutes: durationMinutes,
                    #description: description,
                    #location: location,
                    #url: url,
                    #isAllDay: isAllDay,
                    #timeZone: timeZone,
                    #availability: availability,
                    #recurrenceRule: recurrenceRule,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteRecurring(
    String? eventId,
    int? timestamp,
    String? span,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecurring, [eventId, timestamp, span]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showCreateEventModal({
    String? title,
    int? startDate,
    int? endDate,
    String? description,
    String? location,
    bool? isAllDay,
    String? recurrenceRule,
    String? availability,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showCreateEventModal, [], {
              #title: title,
              #startDate: startDate,
              #endDate: endDate,
              #description: description,
              #location: location,
              #isAllDay: isAllDay,
              #recurrenceRule: recurrenceRule,
              #availability: availability,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
