// Mocks generated by Mockito 5.4.6 from annotations
// in planfit/test/ics_export_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:planfit/core/db/app_database.dart' as _i2;
import 'package:planfit/features/schedule/domain/event_input.dart' as _i5;
import 'package:planfit/features/schedule/domain/event_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEventRow_0 extends _i1.SmartFake implements _i2.EventRow {
  _FakeEventRow_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i3.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.EventRow>> watchBetween(DateTime? from, DateTime? to) =>
      (super.noSuchMethod(
            Invocation.method(#watchBetween, [from, to]),
            returnValue: _i4.Stream<List<_i2.EventRow>>.empty(),
          )
          as _i4.Stream<List<_i2.EventRow>>);

  @override
  _i4.Stream<List<_i2.EventRow>> watchUpcoming(DateTime? from, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#watchUpcoming, [from], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.EventRow>>.empty(),
          )
          as _i4.Stream<List<_i2.EventRow>>);

  @override
  _i4.Future<_i2.EventRow?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i4.Future<_i2.EventRow?>.value(),
          )
          as _i4.Future<_i2.EventRow?>);

  @override
  _i4.Future<List<_i2.EventRow>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i4.Future<List<_i2.EventRow>>.value(<_i2.EventRow>[]),
          )
          as _i4.Future<List<_i2.EventRow>>);

  @override
  _i4.Future<List<_i2.EventRow>> allEvents() =>
      (super.noSuchMethod(
            Invocation.method(#allEvents, []),
            returnValue: _i4.Future<List<_i2.EventRow>>.value(<_i2.EventRow>[]),
          )
          as _i4.Future<List<_i2.EventRow>>);

  @override
  _i4.Future<_i2.EventRow> save(_i5.EventInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#save, [input]),
            returnValue: _i4.Future<_i2.EventRow>.value(
              _FakeEventRow_0(this, Invocation.method(#save, [input])),
            ),
          )
          as _i4.Future<_i2.EventRow>);

  @override
  _i4.Future<void> saveSeriesFrom(String? id, _i5.EventInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#saveSeriesFrom, [id, input]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSeriesFrom(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSeriesFrom, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> restoreEvent(_i2.EventRow? row) =>
      (super.noSuchMethod(
            Invocation.method(#restoreEvent, [row]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> restoreEvents(List<_i2.EventRow>? rows) =>
      (super.noSuchMethod(
            Invocation.method(#restoreEvents, [rows]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
