// Mocks generated by Mockito 5.4.6 from annotations
// in planfit/test/widgets/agenda_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:planfit/core/db/app_database.dart' as _i2;
import 'package:planfit/core/db/daos/todo_dao.dart' as _i5;
import 'package:planfit/features/schedule/domain/event_input.dart' as _i8;
import 'package:planfit/features/schedule/domain/event_repository.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEventRow_0 extends _i1.SmartFake implements _i2.EventRow {
  _FakeEventRow_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_1 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_2 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_3 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_4 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_5 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_6 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EventsTable_7 extends _i1.SmartFake implements _i2.$EventsTable {
  _Fake$EventsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TodoItemsTable_8 extends _i1.SmartFake
    implements _i2.$TodoItemsTable {
  _Fake$TodoItemsTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TodoSubtasksTable_9 extends _i1.SmartFake
    implements _i2.$TodoSubtasksTable {
  _Fake$TodoSubtasksTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTodoDaoManager_10 extends _i1.SmartFake
    implements _i5.TodoDaoManager {
  _FakeTodoDaoManager_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_11<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_12<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_13<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_14<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_15<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_16<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_17<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_18<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_19 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i7.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i2.EventRow>> watchBetween(DateTime? from, DateTime? to) =>
      (super.noSuchMethod(
            Invocation.method(#watchBetween, [from, to]),
            returnValue: _i6.Stream<List<_i2.EventRow>>.empty(),
          )
          as _i6.Stream<List<_i2.EventRow>>);

  @override
  _i6.Stream<List<_i2.EventRow>> watchUpcoming(DateTime? from, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#watchUpcoming, [from], {#limit: limit}),
            returnValue: _i6.Stream<List<_i2.EventRow>>.empty(),
          )
          as _i6.Stream<List<_i2.EventRow>>);

  @override
  _i6.Future<_i2.EventRow?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i6.Future<_i2.EventRow?>.value(),
          )
          as _i6.Future<_i2.EventRow?>);

  @override
  _i6.Future<List<_i2.EventRow>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i6.Future<List<_i2.EventRow>>.value(<_i2.EventRow>[]),
          )
          as _i6.Future<List<_i2.EventRow>>);

  @override
  _i6.Future<List<_i2.EventRow>> allEvents() =>
      (super.noSuchMethod(
            Invocation.method(#allEvents, []),
            returnValue: _i6.Future<List<_i2.EventRow>>.value(<_i2.EventRow>[]),
          )
          as _i6.Future<List<_i2.EventRow>>);

  @override
  _i6.Future<_i2.EventRow> save(_i8.EventInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#save, [input]),
            returnValue: _i6.Future<_i2.EventRow>.value(
              _FakeEventRow_0(this, Invocation.method(#save, [input])),
            ),
          )
          as _i6.Future<_i2.EventRow>);

  @override
  _i6.Future<void> saveSeriesFrom(String? id, _i8.EventInput? input) =>
      (super.noSuchMethod(
            Invocation.method(#saveSeriesFrom, [id, input]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSeriesFrom(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSeriesFrom, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restoreEvent(_i2.EventRow? row) =>
      (super.noSuchMethod(
            Invocation.method(#restoreEvent, [row]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restoreEvents(List<_i2.EventRow>? rows) =>
      (super.noSuchMethod(
            Invocation.method(#restoreEvents, [rows]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [TodoDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoDao extends _i1.Mock implements _i5.TodoDao {
  MockTodoDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_1(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_2(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_3(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i9.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_4(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_5(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_6(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i2.$EventsTable get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _Fake$EventsTable_7(this, Invocation.getter(#events)),
          )
          as _i2.$EventsTable);

  @override
  _i2.$TodoItemsTable get todoItems =>
      (super.noSuchMethod(
            Invocation.getter(#todoItems),
            returnValue: _Fake$TodoItemsTable_8(
              this,
              Invocation.getter(#todoItems),
            ),
          )
          as _i2.$TodoItemsTable);

  @override
  _i2.$TodoSubtasksTable get todoSubtasks =>
      (super.noSuchMethod(
            Invocation.getter(#todoSubtasks),
            returnValue: _Fake$TodoSubtasksTable_9(
              this,
              Invocation.getter(#todoSubtasks),
            ),
          )
          as _i2.$TodoSubtasksTable);

  @override
  _i5.TodoDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeTodoDaoManager_10(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.TodoDaoManager);

  @override
  _i6.Stream<List<_i2.TodoRow>> watchBetween(DateTime? from, DateTime? to) =>
      (super.noSuchMethod(
            Invocation.method(#watchBetween, [from, to]),
            returnValue: _i6.Stream<List<_i2.TodoRow>>.empty(),
          )
          as _i6.Stream<List<_i2.TodoRow>>);

  @override
  _i6.Future<List<_i2.TodoRow>> between(DateTime? from, DateTime? to) =>
      (super.noSuchMethod(
            Invocation.method(#between, [from, to]),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Future<void> upsert(_i2.TodoItemsCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#upsert, [companion]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.TodoRow>> all() =>
      (super.noSuchMethod(
            Invocation.method(#all, []),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Future<_i2.TodoRow?> findById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i6.Future<_i2.TodoRow?>.value(),
          )
          as _i6.Future<_i2.TodoRow?>);

  @override
  _i6.Future<void> patch(String? id, _i2.TodoItemsCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [id, companion]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.TodoRow>> needingReminderPush() =>
      (super.noSuchMethod(
            Invocation.method(#needingReminderPush, []),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Future<_i2.TodoRow?> findByOsReminderId(String? osReminderId) =>
      (super.noSuchMethod(
            Invocation.method(#findByOsReminderId, [osReminderId]),
            returnValue: _i6.Future<_i2.TodoRow?>.value(),
          )
          as _i6.Future<_i2.TodoRow?>);

  @override
  _i6.Future<List<_i2.TodoRow>> linkedToReminders() =>
      (super.noSuchMethod(
            Invocation.method(#linkedToReminders, []),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Future<void> setDone(String? id, bool? done) =>
      (super.noSuchMethod(
            Invocation.method(#setDone, [id, done]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateSlotStart(String? id, DateTime? slotStart) =>
      (super.noSuchMethod(
            Invocation.method(#updateSlotStart, [id, slotStart]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearTime(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#clearTime, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.TodoRow>> seriesFrom(
    String? groupId,
    DateTime? fromSlot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#seriesFrom, [groupId, fromSlot]),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Future<void> deleteSeriesFrom(String? groupId, DateTime? fromSlot) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSeriesFrom, [groupId, fromSlot]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.TodoRow>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Future<void> setPriority(String? id, int? priority) =>
      (super.noSuchMethod(
            Invocation.method(#setPriority, [id, priority]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setTags(String? id, String? tags) =>
      (super.noSuchMethod(
            Invocation.method(#setTags, [id, tags]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setNotify(String? id, bool? notify) =>
      (super.noSuchMethod(
            Invocation.method(#setNotify, [id, notify]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAdditionalReminders(String? id, String? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setAdditionalReminders, [id, minutes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSortOrder(String? id, int? sortOrder) =>
      (super.noSuchMethod(
            Invocation.method(#setSortOrder, [id, sortOrder]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setPinned(String? id, bool? pinned) =>
      (super.noSuchMethod(
            Invocation.method(#setPinned, [id, pinned]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<List<_i2.TodoRow>> watchPinned() =>
      (super.noSuchMethod(
            Invocation.method(#watchPinned, []),
            returnValue: _i6.Stream<List<_i2.TodoRow>>.empty(),
          )
          as _i6.Stream<List<_i2.TodoRow>>);

  @override
  _i6.Future<List<_i2.TodoRow>> completedBefore(DateTime? cutoff) =>
      (super.noSuchMethod(
            Invocation.method(#completedBefore, [cutoff]),
            returnValue: _i6.Future<List<_i2.TodoRow>>.value(<_i2.TodoRow>[]),
          )
          as _i6.Future<List<_i2.TodoRow>>);

  @override
  _i6.Stream<List<_i2.TodoSubtaskRow>> watchSubtasks(String? todoId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSubtasks, [todoId]),
            returnValue: _i6.Stream<List<_i2.TodoSubtaskRow>>.empty(),
          )
          as _i6.Stream<List<_i2.TodoSubtaskRow>>);

  @override
  _i6.Future<List<_i2.TodoSubtaskRow>> allSubtasks() =>
      (super.noSuchMethod(
            Invocation.method(#allSubtasks, []),
            returnValue: _i6.Future<List<_i2.TodoSubtaskRow>>.value(
              <_i2.TodoSubtaskRow>[],
            ),
          )
          as _i6.Future<List<_i2.TodoSubtaskRow>>);

  @override
  _i6.Future<void> upsertSubtask(_i2.TodoSubtasksCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSubtask, [companion]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSubtaskDone(String? id, bool? done) =>
      (super.noSuchMethod(
            Invocation.method(#setSubtaskDone, [id, done]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSubtask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubtask, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<List<_i2.TodoRow>> watchOverdue(DateTime? asOf) =>
      (super.noSuchMethod(
            Invocation.method(#watchOverdue, [asOf]),
            returnValue: _i6.Stream<List<_i2.TodoRow>>.empty(),
          )
          as _i6.Stream<List<_i2.TodoRow>>);

  @override
  _i6.Stream<List<_i2.TodoRow>> watchByMinPriority(int? minPriority) =>
      (super.noSuchMethod(
            Invocation.method(#watchByMinPriority, [minPriority]),
            returnValue: _i6.Stream<List<_i2.TodoRow>>.empty(),
          )
          as _i6.Stream<List<_i2.TodoRow>>);

  @override
  _i6.Future<List<String>> allTags() =>
      (super.noSuchMethod(
            Invocation.method(#allTags, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Stream<List<_i2.TodoRow>> watchByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#watchByTag, [tag]),
            returnValue: _i6.Stream<List<_i2.TodoRow>>.empty(),
          )
          as _i6.Stream<List<_i2.TodoRow>>);

  @override
  _i6.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i6.Stream<T>.empty(),
          )
          as _i6.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i6.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i6.Stream<Set<_i3.TableUpdate>>);

  @override
  _i6.Future<T> doWhenOpened<T>(
    _i6.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_11<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i6.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_12<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_13<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_14<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_15<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_16<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_17<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i6.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i6.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i6.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_18<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_18<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i6.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> transaction<T>(
    _i6.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_11<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<T> exclusively<T>(_i6.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_11<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> batch(_i6.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T> runWithInterceptor<T>(
    _i6.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_11<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_19(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_19(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeUpdateInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeUpdateInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_19(
              this,
              Invocation.method(
                #$writeUpdateInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
